### PR TITLE
Merge pull request #1 from radio-astro/master

### PR DESCRIPTION
**Pull request by o-smirnov**
merging back Gijs's changes

### CODE REVIEW

**Comment by o-smirnov** [comment]
Fuck no. Meant to merge the other way. How do I delete this?

**Comment by o-smirnov** [comment]
OK, made some minor fixes caused by your renaming (some things were called radioradiopadre in the README.md, etc.) Please merge, but no need to re-release.

**Comment by o-smirnov** [comment]
Could you please merge and re-release this?

Also, please make me admin of the repo since at the moment I can't even assign issues to myself.

**Comment by gijzelaerr** [comment]
a prettified version has been merged in the master

**Pull request closed without merging**
