### PR TITLE
Fixes issues 6 and 8

### PR DESCRIPTION
**Pull request by o-smirnov**
https://github.com/radio-astro/radiopadre/issues/6 and https://github.com/radio-astro/radiopadre/issues/8

### CODE REVIEW

**Comment by gijzelaerr** [comment]
aarch. ok, so because if the rebase I did your previous commits are shown here also...

Please do a git pull before you start implementing stuff, and squash commits into one commit. 

I'll fix this one more last time :)

**Comment by gijzelaerr** [comment]
rebased and merged

https://github.com/radio-astro/radiopadre/commit/dd916b11ce49c0513ef657ba8d9feb3316f99722

**Comment by o-smirnov** [comment]
OK, so I do

```
git pull
git merge --no-ff radio-astro-master    # my local branch tracking the master master
# do fantastic work
git commit -a 
# do more fantastic work
git commit -a
```

...and how do I now "squash" the commits before pushing and issuing a pull request?

**Comment by gijzelaerr** [comment]
git rebase -i <SHA1 code of commit *BEFORE* the commits you want to
manipulate>

opens up your favorite editor where you can do all kind of funky history
rewriting shizzle.

2015-05-29 14:11 GMT+02:00 Oleg Smirnov <notifications@github.com>:

> OK, so I do
>
> git pull
> git merge --no-ff radio-astro-master    # my local branch tracking the master master
> # do fantastic work
> git commit -a
> # do more fantastic work
> git commit -a
>
> ...and how do I now "squash" the commits before pushing and issuing a pull
> request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radio-astro/radiopadre/pull/10#issuecomment-106784842>
> .
>



-- 
Gijs Molenaar
http://pythonic.nl

**Pull request closed without merging**
