### PR TITLE
fixes #6

### LINKED ISSUE #6: need quick access to sorted subdirectories
A common use case is something like, get me the most-recently modified directory called "reduction-*", and make a DirList from that. Should be easy to incorporate this elegantly, since a DirList is already a list of directories, and already has sorting facilities (although DirList is always recursive, so also need an option to make it non-recursive).

Perhaps something like:

```
from radiopadre import lsd, lsdr
lsd(pattern="*")     # equivalent to DirList('.',recursive=False)(pattern)
lsdr(pattern="*")    # equivalent to DirList('.',recursive=True)(pattern)
```

The function names are chosen to be reminiscent of  ``ls -d`` and ``ls -dR``. Also, when else do I get a chance to import LSD from a Padre?

Then the use case above is

```
lsd("reduction-*").sort("t")[-1]     # sort by time and get last entry
```

or even with an explicit "alias":

```
lsd("reduction-*").latest()       # since it's such a common use case
```

### PR DESCRIPTION
**Pull request by o-smirnov**
See #6. Why can't it automatically merge? I don't see any obvious conflicts in the diff.

### CODE REVIEW

**Comment by o-smirnov** [comment]
OK I see, conflict resolved from my end.

**Comment by gijzelaerr** [comment]
your master tree diverged from the 'true master'.

**Comment by gijzelaerr** [comment]
please don't commit .idea folders :)

I removed it from your previous commit, but you added it again. It is now in the ignore file also.

**Comment by o-smirnov** [comment]
So what's the best practice for keeping it in sync? To merge the "true master" in I did:

```
git checkout -b radio-astro-master master
git pull https://github.com/radio-astro/radiopadre.git master
git merge --no-ff radio-astro-master
```

which I sort of understand, is this what I need to do every time?

**Comment by gijzelaerr** [comment]
you can have multiple remotes where you fetch from. You can also attach specific branches to specific remote branches that will auto merge on a git pull. Good idea to do try a git pull --rebase before a merge by the way.

What I usually do is just pull in the master, create a work branch, implement what you want and then push to a new remote branch, do PR.

**Comment by o-smirnov** [comment]
Ahh ok, so I can give my local repo two remotes (e.g. o-smirnov/padre and radio-astro/radiopadre), and git pull will attempt to integrate changes from both?

Not sure what --rebase does. So my remote is o-smirnov/padre, and I git pull --rebase my local repo, does it then know to merge in changes from radio-astro/radiopadre as well? Is radio-astro/radiopadre what is referred to as the "upstream" repo for o-smirnov/padre?

**Comment by gijzelaerr** [comment]
rebase will not merge the trees, but try to apply the commits again, which
should work if there are no conflicts.

No you can multiple remotes where you selectivly pull and push from. You
can attach specific branches from remotes to specific local branches that
will automatically be updated with a pull.

Note that a pull is a fetch with an auto merge.



2015-05-26 18:00 GMT+02:00 Oleg Smirnov <notifications@github.com>:

> Ahh ok, so I can give my local repo two remotes (e.g. o-smirnov/padre and
> radio-astro/radiopadre), and git pull will attempt to integrate changes
> from both?
>
> Not sure what --rebase does. So my remote is o-smirnov/padre, and I git
> pull --rebase my local repo, does it then know to merge in changes from
> radio-astro/radiopadre as well? Is radio-astro/radiopadre what is referred
> to as the "upstream" repo for o-smirnov/padre?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radio-astro/radiopadre/pull/7#issuecomment-105577092>.
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by gijzelaerr** [comment]
cleanup, rebase and commited

https://github.com/radio-astro/radiopadre/commit/56d0c962c33768e58723b04a5d6e74df06a68ee3

**Comment by o-smirnov** [comment]
OK, sorry to be obstuse, but how can I make a local branch that tracks radio-astro/radiopadre master?

Basically I want my master to track o-smirnov/padre master, and my own radio-astro-master branch to track  radio-astro/radiopadre master.

**Comment by gijzelaerr** [comment]
```
$ cat .git/config 
[...]
[remote "origin"]
	url = git@github.com:radio-astro/radiopadre.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[remote "oleg"]
	url = git@github.com:o-smirnov/padre.git
	fetch = +refs/heads/*:refs/remotes/oleg/*
[branch "oleg"]
	remote = origin
	merge = refs/heads/master
```

**Comment by gijzelaerr** [comment]
oops, updated copy paste, contained error

**Comment by o-smirnov** [comment]
Oh fuck's sake, I'm still missing something here. So I changed my .git config to:

```
[remote "origin"]
        url = git@github.com:o-smirnov/padre.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master

[remote "radio-astro"]
    url = git@github.com:radio-astro/radiopadre.git
    fetch = +refs/heads/*:refs/remotes/origin/*

[branch "radio-astro-master"]
    remote = radio-astro
    merge = refs/heads/master
```

Then did a ``git pull`` to bring in your changes from radio-astro/master. This created conflicts (don't see why, as they were simply cases of extra lines being inserted in the radio-astro/master version). Resolved conflicts, but then when I git pushed, the damn thing created a radio-astro-master branch in radio-astro/radiopadre. 

This is not what I want. All I want is a quick way to merge your commits on radio-astro/radiopadre master into o-smirnov/padre master. Still don't have a good feeling for what the workflow should be...

**Comment by gijzelaerr** [comment]
Will look monday

Op vr 29 mei 2015 20:55 schreef Oleg Smirnov <notifications@github.com>:

**Pull request closed without merging**
