### PR TITLE
fixes issue 19

### PR DESCRIPTION
**Pull request by o-smirnov**
Pity the diff is screwed, the changes are actually minimal...

### CODE REVIEW

**Comment by gijzelaerr** [comment]
I thought I replied to this. If you add such an argument to `setup()` setuptools will manage the script installation for you:

https://github.com/transientskp/tkp/blob/master/setup.py#L53

**Comment by o-smirnov** [comment]
OK did that.

**Comment by gijzelaerr** [comment]
did you test it? running python setup.py install

**Comment by o-smirnov** [comment]
Yup, works for me...

**Pull request merged**
